[package]
name = "tetorica-mdrop-cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "tetorica-mdrop"
path = "src/main.rs"

[dependencies]
tetorica-mdrop-core = { path = "../src-core" }
clap = { version = "4", features = ["derive"] }
tokio = { version = "1", features = ["full"] }

[features]
default = []
dev_web = ["tetorica-mdrop-core/dev_web"]
