[package]
name = "tetorica-mdrop-cli"
version = "0.5.8"
edition = "2021"

[[bin]]
name = "tetorica-mdrop"
path = "src/main.rs"

[dependencies]
tetorica-mdrop-core = { path = "../src-core" }
clap = { version = "4", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0.228", features = ["derive"] }
toml = "1.1.2"

[features]
default = []
dev_web = ["tetorica-mdrop-core/dev_web"]
